### Q1: (Printing and Input)
Print your name and age using two print statements.

In [2]:
print("My name is Oshan Bajracharya and I am 21 Years old.")

My name is Oshan Bajracharya and I am 21 Years old.


### Q2: (Printing and Input)
Print the result of 10 + 20.

In [3]:
print(10+20)

30


### Q3: (Printing and Input)
Use `input()` to take a user's name and greet them.

In [ ]:
greeting = input("Enter your greeting: ")
print(f"{greeting} Oshan Bajracharya")


### Q4: (Printing and Input)
Input two numbers and print their sum.

In [7]:
a= input("Enter first number: ")
b = input("Enter second number: ")
print(f"The sum of {a} and {b} is {int(a) + int(b)}")

The sum of 10 and 20 is 30


### Q5: (Printing and Input)
Ask for a favorite color and print it twice using multiplication.

In [ ]:
f_color = input("Enter your favorite color: ")
print(f"{f_color}*2")

### Q6: (Printing and Input)
Ask the user to input a sentence and print its length.

In [ ]:
sen = input("Enter a sentence: ")
print(f"The length of the sentence {sen} is {len(sen)} characters.")

### Q7: (Variable and Data Types)
Create a variable for each type: int, float, string, bool. Print them.

In [9]:
a=int(10)
b=float(20.5)
c="oshan"
d=True
print(f"Variable a is of type {type(a)}")
print(f"Variable b is of type {type(b)}")
print(f"Variable c is of type {type(c)}")
print(f"Variable d is of type {type(d)}")

Variable a is of type <class 'int'>
Variable b is of type <class 'float'>
Variable c is of type <class 'str'>
Variable d is of type <class 'bool'>


### Q8: (Variable and Data Types)
Assign the value 10 to x and then add 5 to it. Print the result.

In [ ]:
a = int(input("Enter value for x: "))
assign=a+10

### Q9: (Variable and Data Types)
Check the type of variable `val = 3.14`.

In [10]:
val = 3.14
print(type(val))

<class 'float'>


### Q10: (Variable and Data Types)
Use multiple assignment to assign 3 values to a, b, c.

In [ ]:
a, b, c = 10, 20, 30
print(a,b,c)

### Q11: (Complex Numbers)
Create complex numbers x = 2+3j and y = 4-2j. Print their sum.

In [11]:
complex1 = 3 + 4j
complex2 = 5 + 6j
print(complex1 + complex2)

(8+10j)


### Q12: (Complex Numbers)
Print the real and imaginary parts of 5 + 7j.

In [12]:
comp=5+7j
print(comp.real)
print(comp.imag)

5.0
7.0


### Q13: (Complex Numbers)
Multiply two complex numbers: (1+2j)*(3+4j) and print the result.

In [13]:
complex1 = 3 + 4j
complex2 = 5 + 6j
print(complex1 * complex2)

(-9+38j)


### Q14: (If-Else and Comparisons)
Check if the number 12 is greater than 10 and print a message.

In [ ]:
if 12>10:
    print("12 is greater than 10")
else:
    print("12 is not greater than 10")

### Q15: (If-Else and Comparisons)
Ask for an age and print whether the person is an adult or not.

In [ ]:
age=int(input("Enter your age: "))
if age >= 18:
    print("you are adult")
else:
    print("you are not adult")

### Q16: (If-Else and Comparisons)
Check if a number is even or odd.

In [ ]:
num = int(input("Enter a number: "))
if num % 2 == 0:
    print(f"{num} is an even number")
else:
    print(f"{num} is an odd number")

### Q17: (If-Else and Comparisons)
Compare two input numbers and print which is larger.

In [ ]:
num1 = int(input("Enter a number: "))
num2 = int(input("Enter another number: "))
if num1 > num2:
    print(f"{num1} is greater than {num2}")
elif num1 < num2:
    print(f"{num1} is less than {num2}")
else:
    print(f"{num1} is equal to {num2}")


### Q18: (Loops)
Print numbers from 1 to 10 using a for loop.

In [14]:
for a in  range(1, 11):
    print(a)

1
2
3
4
5
6
7
8
9
10


### Q19: (Loops)
Print all even numbers from 0 to 20.

In [16]:
for a in  range(1, 21):
    print(a)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20


### Q20: (Loops)
Print the multiplication table of 7.

In [3]:
for x in range(1, 11):
 x=x*7
 print(x)




7
14
21
28
35
42
49
56
63
70


### Q21: (Loops)
Use a while loop to print numbers from 5 to 1.

In [27]:
for i in range(5,0,-1):
    print(i)

5
4
3
2
1


### Q22: (Loops)
Print the characters of a string one by one using a loop.

In [166]:
a = "oshan"
for a in a:
    print(a)

o
s
h
a
n


### Q23: (String Operations)
Concatenate 'Hello' and 'World' and print.

In [30]:
con1 = "Hello"
con2 = "World"
print(con1 + " " + con2)

Hello World


### Q24: (String Operations)
Repeat the word 'Yes' 4 times using *.

In [32]:
print("YES \n"*4 )

YES 
YES 
YES 
YES 



### Q25: (String Operations)
Find the length of a string input by user.

In [ ]:
a= input("Enter a string: ")
print(f"The length of the string '{a}' is {len(a)} characters.")

### Q26: (String Operations)
Access and print the first and last character of a string.

In [38]:
a ="Hello, World!"
print(a[0],a[len(a)-1])


H !


### Q27: (Lists)
Create a list of 5 fruits and print the third item.

In [ ]:
friuts =["apple",'banana',"man","lichi","pineapple"]
print(friuts[2])

mango


### Q28: (Lists)
Add 'mango' to the list and print.

In [40]:
friut =["apple",'banana',"man","lichi","pineapple"]
friut.append("mango")
print(friut)

['apple', 'banana', 'man', 'lichi', 'pineapple', 'mango']


### Q29: (Lists)
Remove the first item of the list and print the rest.

In [42]:
friut.pop(0)
print(friut)

['man', 'lichi', 'pineapple', 'mango']


### Q30: (Lists)
Sort a list of numbers in descending order.

In [83]:
list1=[1,2,3,4,5]
list.reverse()
print(list)


[5, 4, 3, 2, 1]


### Q31: (Lists)
Print every second item from a list using slicing.

In [82]:
list1=[1,2,3,4,5]
print(list1[::2])


[1, 3, 5]


### Q32: (Tuples)
Create a tuple with 4 numbers and print its last item.

In [67]:
tup= (1,2,3,4)
print(tup[:])


(1, 2, 3, 4)


### Q33: (Tuples)
Try changing the value of an item in a tuple and observe the error.

In [ ]:
tup= (1,2,3,4)
tup[1]=5
print(tup)


### Q34: (Tuples)
Convert a tuple to a list, change a value, and convert it back.

In [ ]:

tup =(1, 2, 3, 4)
a = list(tup)
a[2] = 8
tup1 = tuple(a)  
print(tup1)




### Q35: (Sets)
Create a set of 3 elements and add one more element.

In [88]:
set1={1,2,3}
set2={4}
a=set1.union(set2)
print(a)

{1, 2, 3, 4}


### Q36: (Sets)
Try adding a duplicate and print the set.

In [ ]:
SET={3}
SET.add(3)
print(SET)


{3}


### Q37: (Sets)
Perform union of two sets {1,2,3} and {3,4,5}.

### Q38: (Dictionaries)
Create a dictionary for a student with name, age, grade. Print the dictionary.

In [ ]:
set1={1,2,3}
set2={3,4,5}
print(set1.union(set2))

In [104]:
dis={'name':"Oshan",
     "Age":21,
     "grade":"BE"}
print(dis)

{'name': 'Oshan', 'Age': 21, 'grade': 'BE'}


### Q39: (Dictionaries)
Access the age from the dictionary.

In [110]:
print(dis["Age"])

21


### Q40: (Dictionaries)
Update the grade of the student.

In [111]:
dis["grade"] = 12
print(dis)

{'name': 'Oshan', 'Age': 21, 'grade': 12}


### Q41: (Dictionaries)
Add a new key 'subject' to the dictionary.

In [114]:
dis["city"] = "KTM"
print(dis)

{'name': 'Oshan', 'Age': 21, 'grade': 12, 'city': 'KTM'}


### Q42: (Indexing and Slicing)
Create a list of numbers and print elements from index 1 to 4.

In [117]:
lst=[1,2,3,4,"jdjj",3.3,True]
print(lst[:4])


[1, 2, 3, 4]


### Q43: (Indexing and Slicing)
Access every second element in the list.

In [118]:
lst=[1,2,3,4,"jdjj",3.3,True]
print(lst[::2])


[1, 3, 'jdjj', True]


### Q44: (Indexing and Slicing)
Print the last three characters of the string 'Programming'.

In [128]:
string="Programming"
a=string[len(string)-3:len(string)]
print(a)


ing


### Q45: (Nested Structures)
Create a nested list and print the second element of the first list.

In [130]:
lis=[1,2,3,[2,5,6]]
print(lis[3])

[2, 5, 6]


### Q46: (Nested Structures)
Create a nested dictionary and access a nested value.

In [132]:
dis={
    "person1":{"name":"Oshan"},
    "person2":{"name":"Bibek"},
    "person3":{"name":"Shankha"},
    "person4":{"name":"Priya"}

}
print(dis["person1"]["name"])

Oshan


### Q47: (NumPy Basics)
Import numpy and create a 1D array from 0 to 9.

In [139]:
import numpy as np
np.array([0,1,2,3,4,5,6,7,8,9])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Q48: (NumPy Basics)
Create a 2D array with shape (2,3).

In [ ]:
arr=np.array([[1,2,3],[4,5,6]])


(2, 3)


### Q49: (NumPy Basics)
Print the shape and dtype of an array.

In [141]:
print(arr.shape)
print(arr.dtype)

(2, 3)
int64


### Q50: (NumPy Basics)
Use np.linspace to create 5 values from 1 to 10.

In [156]:

arr = np.linspace(1, 10, num=10)
print(arr)
np.linspace(1, 10, 5)


[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

### Q51: (NumPy Basics)
Generate a random array of shape (3,3).

In [154]:
import random as ran

arr=np.random.randint(1,99,size=(3,3))
print(arr)

[[52  2 49]
 [ 8 61 45]
 [51 22 34]]


### Q52: (NumPy Basics)
Find the maximum and mean of a numpy array.

In [148]:
print(arr.max())
print(arr.mean())

6
3.5


### Q53: (NumPy Basics)
Access element at row 1, col 2 in a 2D array.

In [144]:
print(arr[0,1])

2


### Q54: (NumPy Basics)
Flatten a 2D array.

In [146]:
print(arr.flatten())

[1 2 3 4 5 6]


### Q55: (NumPy Basics)
Stack two arrays vertically.

In [158]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
result = np.vstack((a, b))
print(result)


[[1 2 3]
 [4 5 6]]


### Q56: (NumPy Basics)
Slice the first two rows of a 2D numpy array.

In [ ]:
print(arr[1:4])

array([], shape=(0, 3), dtype=int64)

### Q57: (NumPy Basics)
Slice the first two rows of a 2D numpy array.

In [163]:
arr[0:2, :]


array([[1, 2, 3],
       [4, 5, 6]])

### Q58: (NumPy Basics)
Print the shape and dtype of an array.

In [162]:
arr = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
print(arr.shape)
print(arr.dtype)

(3, 3)
int64


### Q59: (String Operations)
Repeat the word 'Yes' 4 times using *.

In [ ]:
print("yes"*4)

### Q60: (Variable and Data Types)
Use multiple assignment to assign 3 values to a, b, c.

In [ ]:
a,b,c=1,1,2

### Q61: (Dictionaries)
Add a new key 'subject' to the dictionary.

In [ ]:
dis['subject']="Python"

### Q62: (Variable and Data Types)
Assign the value 10 to x and then add 5 to it. Print the result.

In [164]:
num=int(input("enter num :"))
num=num+10
print(num)

15


### Q63: (Nested Structures)
Create a nested list and print the second element of the first list.

In [165]:
lis=[1,2,3,[2,5,6]]
print(lis[3][0])

2


### Q64: (Loops)
Print the characters of a string one by one using a loop.

In [ ]:
lis=[1,2,3,[2,5,6]]
print(lis[3])

### Q65: (Sets)
Try adding a duplicate and print the set.

In [ ]:
SET={3}
SET.add(3)
print(SET)


### Q66: (NumPy Basics)
Flatten a 2D array.

In [ ]:
arr.flatten()

### Q67: (Printing and Input)
Ask for a favorite color and print it twice using multiplication.

In [ ]:
colr=input("enter color")
print(f_color*2)

### Q68: (String Operations)
Repeat the word 'Yes' 4 times using *.

In [ ]:
print("yes"*4)

### Q69: (Printing and Input)
Ask for a favorite color and print it twice using multiplication.

In [ ]:
colr=input("enter color")
print(f_color*2)

### Q70: (If-Else and Comparisons)
Check if a number is even or odd.

In [ ]:
a=2
if a%2==0:
    print("even")
else:
    print("odd")

### Q71: (NumPy Basics)
Import numpy and create a 1D array from 0 to 9.

In [ ]:
import numpy as np
D1=np.array([0,1,2,3,4,5,6,7,8,9])

### Q72: (Loops)
Use a while loop to print numbers from 5 to 1.

In [174]:
n=5
while(n>=1):
  print(n)
  n=n-1

5
4
3
2
1


### Q73: (If-Else and Comparisons)
Check if the number 12 is greater than 10 and print a message.

In [175]:
if 12>10:
    print("12 is greater than 10")
else:
    print("12 is not greater than 10")

12 is greater than 10


### Q74: (Indexing and Slicing)
Access every second element in the list.

In [167]:
lis=[1,2,[3,4,5]]
print(lis[2])

[3, 4, 5]


### Q75: (Loops)
Use a while loop to print numbers from 5 to 1.

In [176]:
n=5
while(n>=1):
  print(n)
  n=n-1

5
4
3
2
1


### Q76: (Printing and Input)
Print the result of 10 + 20.

In [ ]:
print(10+20)

### Q77: (Printing and Input)
Ask for a favorite color and print it twice using multiplication.

In [ ]:
colr=input("enter color")
print(f_color*2)

### Q78: (Lists)
Remove the first item of the list and print the rest.

In [177]:
lsi=[1,2,3]
lsi.remove(1)
print(lsi)

[2, 3]


### Q79: (NumPy Basics)
Use np.linspace to create 5 values from 1 to 10.

In [ ]:
import numpy as np

arr = np.linspace(1, 10, num=10) 
print(arr)

np.linspace(1, 10, 5)



### Q80: (Complex Numbers)
Create complex numbers x = 2+3j and y = 4-2j. Print their sum.

In [ ]:
x=2+3j
y=4-2j
print(x+y)

### Q81: (Printing and Input)
Ask for a favorite color and print it twice using multiplication.

In [ ]:
colr=input("enter color")
print(f_color*2)

### Q82: (Complex Numbers)
Create complex numbers x = 2+3j and y = 4-2j. Print their sum.

In [ ]:
x=2+3j
y=4-2j
print(x+y)

### Q83: (Dictionaries)
Access the age from the dictionary.

In [ ]:
print(dis["Age"])

### Q84: (Lists)
Create a list of 5 fruits and print the third item.

In [ ]:
fri=['apple',"banana","mango","lichi","sother"]
print(fri[2])

### Q85: (NumPy Basics)
Stack two arrays vertically.

In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

result = np.vstack((a, b))
print(result)


### Q86: (Loops)
Use a while loop to print numbers from 5 to 1.

In [ ]:
n=5
while(n>=1):
  print(n)
  n=n-1

### Q87: (Lists)
Remove the first item of the list and print the rest.

In [ ]:
lsi=[1,2,3]
lsi.remove(1)
print(lsi)

### Q88: (Lists)
Create a list of 5 fruits and print the third item.

In [ ]:
friut =["apple",'banana',"man","lichi","pineapple"]
friut.append("mango")
print(friut)

### Q89: (Printing and Input)
Ask for a favorite color and print it twice using multiplication.

In [ ]:
colr=input("enter color")
print(f_color*2)

### Q90: (Tuples)
Convert a tuple to a list, change a value, and convert it back.

In [ ]:

tup =(1, 2, 3, 4)
a = list(tup)
a[2] = 8
tup1 = tuple(a)  
print(tup1)




### Q91: (NumPy Basics)
Import numpy and create a 1D array from 0 to 9.

In [ ]:
import numpy as np
a=np.arr([0,1,2,3,4,5,6,7,8,9])

### Q92: (Variable and Data Types)
Use multiple assignment to assign 3 values to a, b, c.

In [ ]:
a,b,c=1,2,3

### Q93: (Variable and Data Types)
Check the type of variable `val = 3.14`.

In [ ]:
val = 3.14
print(type(val))

### Q94: (Tuples)
Convert a tuple to a list, change a value, and convert it back.

In [ ]:

tup =(1, 2, 3, 4)
a = list(tup)
a[2] = 8
tup1 = tuple(a)  
print(tup1)




### Q95: (If-Else and Comparisons)
Compare two input numbers and print which is larger.

In [ ]:
num = int(input("Enter a number: "))
if num % 2 == 0:
    print(f"{num} is an even number")
else:
    print(f"{num} is an odd number")

### Q96: (Sets)
Try adding a duplicate and print the set.

In [178]:
set={1,2,3}
set.add(3)
print(set)

{1, 2, 3}


### Q97: (Dictionaries)
Access the age from the dictionary.

In [ ]:
print(dis["Age"])

### Q98: (Lists)
Add 'mango' to the list and print.

In [ ]:
friut =["apple",'banana',"man","lichi","pineapple"]
friut.append("mango")
print(friut)

### Q99: (Sets)
Create a set of 3 elements and add one more element.

In [ ]:
set={1,2,3}
set.add(4)
print(set)

### Q100: (If-Else and Comparisons)
Compare two input numbers and print which is larger.

In [ ]:
num1 = int(input("Enter a number: "))
num2 = int(input("Enter another number: "))
if num1 > num2:
    print(f"{num1} is greater than {num2}")
elif num1 < num2:
    print(f"{num1} is less than {num2}")
else:
    print(f"{num1} is equal to {num2}")
