<center>Part A: Logistic Regression</center>

<b>Dataset</b><br>
Use the Breast Cancer dataset available in Scikit-learn.<br>
<b>Task 1: Load the Dataset</b><br>
from sklearn.datasets import <br>load_breast_cancer<br>
data = load_breast_cancer()<br>
X = data.data<br>
y = data.target<br>

In [59]:
import pandas as pd
from pandas.core.frame import DataFrame
from sklearn.datasets import load_breast_cancer

data = load_breast_cancer()

# Create DataFrame from the dataset
df = DataFrame(data.data, columns=data.feature_names)

X = data.data
Y = data.target

<b>ask 2: Explore the Dataset</B><br>
1. Display the shape of X and y.
2. Print the first five rows.
3. Identify:<br>
o Number of samples<br>
o Number of features<br>
o Number of classes

In [60]:
# Display the shape of X and Y.
print(X.shape,Y.shape)
# print the first five row
print(df.head())

'''
Identify:
o Number of samples
o Number of features
o Number of classes
 '''
data = load_breast_cancer()

X = data.data
Y = data.target
print("Number of samples:", X.shape[0])
print("Number of features:", X.shape[1])
print("Number of classes:", len(data.target_names))

(569, 30) (569,)
   mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst radius  worst texture  worst perimete

<b>Task 3: Split the Dataset
Split the dataset into:</B>
* 80% training
* 20% testing <br>
(Note: import `train_test_split` from `sklearn.model_selection`, identify the function and use it to
split the dataset into Training data and testing data)

In [61]:
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split

# Load dataset
data = load_breast_cancer()
X = data.data
Y = data.target

# Split dataset: 80% training, 20% testing
X_train, X_test, Y_train, Y_test = train_test_split(
    X, Y,
    test_size=0.2,      # 20% for testing
    random_state=42     # for reproducible results
)
# Display shapes
print("Training features shape:", X_train.shape)
print("Testing features shape:", X_test.shape)
print("Training labels shape:", Y_train.shape)
print("Testing labels shape:", Y_test.shape)
# Load dataset
data = load_breast_cancer()

X = data.data
Y = data.target

# Split dataset: 80% training, 20% testing
X_train, X_test, Y_train, Y_test = train_test_split(
    X, Y,
    test_size=0.2,      # 20% for testing
    random_state=42     # for reproducible results
)

# Display shapes
print("Training features shape:", X_train.shape)
print("Testing features shape:", X_test.shape)
print("Training labels shape:", Y_train.shape)
print("Testing labels shape:", Y_test.shape)

Training features shape: (455, 30)
Testing features shape: (114, 30)
Training labels shape: (455,)
Testing labels shape: (114,)
Training features shape: (455, 30)
Testing features shape: (114, 30)
Training labels shape: (455,)
Testing labels shape: (114,)


<b>Task 4: Standardize Features</B><br>
Apply feature scaling using .<br>StandardScaler as you did in previous lab (Lab 2).<br>
(Note: import StandardScaler from sklearn.preprocessing)

In [62]:
from sklearn.preprocessing  import StandardScaler

# Create scaler object
scaler = StandardScaler()

# Fit on training data and transform
X_train_scaled = scaler.fit_transform(X_train)

# Transform testing data using the same scaler
X_test_scaled = scaler.transform(X_test)

# Check shapes
print("Scaled Training Features Shape:", X_train_scaled.shape)
print("Scaled Testing Features Shape:", X_test_scaled.shape)

Scaled Training Features Shape: (455, 30)
Scaled Testing Features Shape: (114, 30)


<b>Task 5: Train Logistic Regression Model</b><br>
Train the logistic regression model using default parameters.<br>
(Note: import LogisticRegression from sklearn.linear_model)

In [63]:
from sklearn.linear_model  import LogisticRegression
# Create the model
model = LogisticRegression()
# Train the model using the scaled training data
model.fit(X_train_scaled, Y_train)
print("Logistic Regression model trained successfully!")

Logistic Regression model trained successfully!


<b>Task 6: Make Predictions</b><br>
Predict class labels for the test set.

In [64]:
# Predict class labels for the test set
Y_pred = model.predict(X_test_scaled)
# Display first 10 predictions
print("Predicted labels:", Y_pred[:10])
print("Actual labels:   ", Y_test[:10])


Predicted labels: [1 0 0 1 1 0 0 0 1 1]
Actual labels:    [1 0 0 1 1 0 0 0 1 1]


<b>Task 7: Evaluate the Model</B><br>
Compute following parameters to evaluate your model:
1. Accuracy
2. Precision
3. Recall
4. F1-score
5. Confusion Matrix <br>
(Note: import accuracy_score from sklearn.metrics)

In [65]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix
)

# Calculate evaluation metrics
accuracy = accuracy_score(Y_test, Y_pred)
precision = precision_score(Y_test, Y_pred)
recall = recall_score(Y_test, Y_pred)
f1 = f1_score(Y_test, Y_pred)
cm = confusion_matrix(Y_test, Y_pred)

# Print results
print("Accuracy :", accuracy)
print("Precision:", precision)
print("Recall   :", recall)
print("F1-Score :", f1)

print("\nConfusion Matrix:")
print(cm)

Accuracy : 0.9736842105263158
Precision: 0.9722222222222222
Recall   : 0.9859154929577465
F1-Score : 0.9790209790209791

Confusion Matrix:
[[41  2]
 [ 1 70]]


<b>Task 8: Interpret Coefficients</b><br>
Display the coefficients of the trained model.<br>

Questions:<br>
1. Which feature has the largest positive coefficient?
2. Which feature has the largest negative coefficient?
3. What does the sign of a coefficient indicate?

In [66]:
import numpy as np

# Display coefficients
for feature, coef in zip(data.feature_names, model.coef_[0]):
    print(f"{feature}: {coef}")

# Largest positive coefficient
max_idx = np.argmax(model.coef_[0])
print("\n1. Largest positive coefficient:")
print(data.feature_names[max_idx], model.coef_[0][max_idx])

# Largest negative coefficient
min_idx = np.argmin(model.coef_[0])
print("\n2. Largest negative coefficient:")
print(data.feature_names[min_idx], model.coef_[0][min_idx])

# 3. Interpretation
print("\n3. Sign of coefficient:")
print("Positive (+): Feature increases likelihood of class 1 (Benign)")
print("Negative (-): Feature increases likelihood of class 0 (Malignant)")

mean radius: -0.4319036777743386
mean texture: -0.3873255311413923
mean perimeter: -0.3934324764249616
mean area: -0.4652100607636062
mean smoothness: -0.07166727707542121
mean compactness: 0.5401639468319589
mean concavity: -0.8014580988560307
mean concave points: -1.1198040756502856
mean symmetry: 0.23611851556028884
mean fractal dimension: 0.07592092813647588
radius error: -1.2681781455073828
texture error: 0.18887738010991295
perimeter error: -0.6105830174385635
area error: -0.9071857032866862
smoothness error: -0.31330675348779824
compactness error: 0.6824914543472089
concavity error: 0.1752745171367217
concave points error: -0.3112998998152255
symmetry error: 0.5004250240524784
fractal dimension error: 0.6162299296594608
worst radius: -0.879840235250774
worst texture: -1.3506055922623306
worst perimeter: -0.5894527319656228
worst area: -0.8418459407075642
worst smoothness: -0.5441696698296026
worst compactness: 0.016110194289949604
worst concavity: -0.9430531344506452
worst conca

<center>  Part B: Support Vector Classification (SVC)</center>

<b> Dataset </b><bR>
Use the iris datasets
<b>Task 1: Load Dataset </b><br>
(Note: import load_iris from sklearn.datasets and use function )

In [67]:
from sklearn.datasets import load_iris

# Load the Iris dataset
data = load_iris()

# Features and target
X = data.data
Y = data.target

print("Dataset loaded successfully!")

Dataset loaded successfully!


<br>Task 2: Exploratory Analysis</b><br>
Determine:
1. Number of classes
2. Number of features
3. Class labels

In [68]:
# Number of classes
print("Number of classes:", len(data.target_names))

# Number of features
print("Number of features:", len(data.feature_names))

# Class labels
print("Class labels:", data.target_names)

Number of classes: 3
Number of features: 4
Class labels: ['setosa' 'versicolor' 'virginica']


<b>Task 3: Train-Test Split
Use:</b><br>

* 70% training
* 30% testing

In [69]:
from sklearn.model_selection import train_test_split

# Split dataset into 70% training and 30% testing
X_train, X_test, Y_train, Y_test = train_test_split(
    X, Y,
    test_size=0.3,
    random_state=42
)

print("Training set shape:", X_train.shape)
print("Testing set shape:", X_test.shape)

Training set shape: (105, 4)
Testing set shape: (45, 4)


<b>Task 4: Standardize Features</b><br>
Apply StandardScaler.

In [70]:
from sklearn.preprocessing import StandardScaler

# Initialize scaler
scaler = StandardScaler()

# Fit on training data and transform it
X_train_scaled = scaler.fit_transform(X_train)

# Transform test data
X_test_scaled = scaler.transform(X_test)

# Output confirmation
print("Standardization completed successfully")

Standardization completed successfully


<b>Task 5: Train Linear SVM</b><br>


from sklearn.svm import SVC<br>
svc_linear = SVC(kernel='linear')<br>
Train the model.

In [71]:
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC

# Task 4: Standardize Features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Task 5: Train Linear SVM
svc_linear = SVC(kernel='linear')
svc_linear.fit(X_train_scaled, Y_train)

print("Model trained successfully!")

Model trained successfully!


<b>Task 6: Evaluate the Linear SVM</b><br>
Calculate:
1. Accuracy
2. Confusion Matrix
3. Classification Report

In [74]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Predictions
Y_pred = svc_linear.predict(X_test_scaled)

# 1. Accuracy
accuracy = accuracy_score(Y_test, Y_pred)
print("Accuracy:", accuracy)

# 2. Confusion Matrix
cm = confusion_matrix(Y_test, Y_pred)
print("\nConfusion Matrix:\n", cm)

# 3. Classification Report
print("\nClassification Report:\n")
print(classification_report(Y_test, Y_pred))

Accuracy: 0.9777777777777777

Confusion Matrix:
 [[19  0  0]
 [ 0 12  1]
 [ 0  0 13]]

Classification Report:

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      0.92      0.96        13
           2       0.93      1.00      0.96        13

    accuracy                           0.98        45
   macro avg       0.98      0.97      0.97        45
weighted avg       0.98      0.98      0.98        45



<b>Task 7: Train RBF Kernel SVM</b><br>
svc_rbf = SVC(kernel='rbf')<br>
Train and evaluate.

In [75]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Train RBF Kernel SVM
svc_rbf = SVC(kernel='rbf')
svc_rbf.fit(X_train_scaled, Y_train)

# Predictions
Y_pred_rbf = svc_rbf.predict(X_test_scaled)

# Evaluation

# 1. Accuracy
accuracy = accuracy_score(Y_test, Y_pred_rbf)
print("Accuracy:", accuracy)

# 2. Confusion Matrix
cm = confusion_matrix(Y_test, Y_pred_rbf)
print("\nConfusion Matrix:\n", cm)

# 3. Classification Report
print("\nClassification Report:\n")
print(classification_report(Y_test, Y_pred_rbf))

Accuracy: 1.0

Confusion Matrix:
 [[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]

Classification Report:

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00        13

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45



<b>Task 8: Compare Kernels</b><br>
Create a table for the coparison of Accuracy that you can achieve when using Linear or RBF
Kernel:<br>

| Kernel | Accuracy |
|----|-------|
| Linear  |  |   
| RBF   |    |   


In [76]:
import pandas as pd
from sklearn.metrics import accuracy_score

# Accuracy for Linear SVM
y_pred_linear = svc_linear.predict(X_test_scaled)
acc_linear = accuracy_score(Y_test, y_pred_linear)

# Accuracy for RBF SVM
y_pred_rbf = svc_rbf.predict(X_test_scaled)
acc_rbf = accuracy_score(Y_test, y_pred_rbf)

# Create comparison table
comparison_table = pd.DataFrame({
    "Kernel": ["Linear", "RBF"],
    "Accuracy": [acc_linear, acc_rbf]
})

print(comparison_table)

   Kernel  Accuracy
0  Linear  0.977778
1     RBF  1.000000


<b>Task 9: Hyperparameter Tuning</B><br>
Experiment with:<br>
C = [0.1,1,10,100]

<br>Record accuracy for each value.

| C | Accuracy |
|----|-------|
|0.1  |  |   
| 1   |    |  
|10|  |
|100 | |

In [77]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
import pandas as pd

C_values = [0.1, 1, 10, 100]
results = []

for C in C_values:
    model = SVC(kernel='linear', C=C)
    model.fit(X_train_scaled, Y_train)

    Y_pred = model.predict(X_test_scaled)
    acc = accuracy_score(Y_test, Y_pred)

    results.append([C, acc])

# Create table
df_results = pd.DataFrame(results, columns=["C", "Accuracy"])

print(df_results)

       C  Accuracy
0    0.1  1.000000
1    1.0  0.977778
2   10.0  0.977778
3  100.0  1.000000


<center>Part C: Support Vector Regression (SVR)</center>

<b>Dataset</b><br>
Use the California Housing dataset<br>
from sklearn.datasets import fetch_california_housing

<b>Task 1: Load Dataset
Display:</b><br>
1. Number of observations
2. Number of features
3. Description of the target variable

In [78]:
from sklearn.datasets import fetch_california_housing

# Load dataset
data = fetch_california_housing()

# 1. Number of observations
print("Number of observations:", data.data.shape[0])

# 2. Number of features
print("Number of features:", data.data.shape[1])

# 3. Description of target variable
print("\nTarget variable description:")
print(data.DESCR)

Number of observations: 20640
Number of features: 8

Target variable description:
.. _california_housing_dataset:

California Housing dataset
--------------------------

**Data Set Characteristics:**

:Number of Instances: 20640

:Number of Attributes: 8 numeric, predictive attributes and the target

:Attribute Information:
    - MedInc        median income in block group
    - HouseAge      median house age in block group
    - AveRooms      average number of rooms per household
    - AveBedrms     average number of bedrooms per household
    - Population    block group population
    - AveOccup      average number of household members
    - Latitude      block group latitude
    - Longitude     block group longitude

:Missing Attribute Values: None

This dataset was obtained from the StatLib repository.
https://www.dcc.fc.up.pt/~ltorgo/Regression/cal_housing.html

The target variable is the median house value for California districts,
expressed in hundreds of thousands of dollars ($1

<b>Task 2: Split Dataset</b><br>
Use:
* 80% training
* 20% testing

In [79]:
from sklearn.model_selection import train_test_split
from sklearn.datasets import fetch_california_housing

# Load dataset
data = fetch_california_housing()

X = data.data
Y = data.target

# Split dataset (80% train, 20% test)
X_train, X_test, Y_train, Y_test = train_test_split(
    X, Y,
    test_size=0.2,
    random_state=42
)

print("Training set shape:", X_train.shape)
print("Testing set shape:", X_test.shape)

Training set shape: (16512, 8)
Testing set shape: (4128, 8)


<b>Task 3: Standardize Features</b><br>
Apply StandardScaler to input features.

In [80]:
from sklearn.preprocessing import StandardScaler

# Create scaler
scaler = StandardScaler()

# Fit on training data and transform
X_train_scaled = scaler.fit_transform(X_train)

# Transform test data
X_test_scaled = scaler.transform(X_test)

print("Feature scaling completed successfully")

Feature scaling completed successfully


<b>Task 4: Train Linear SVR</B><br>
from sklearn.svm import SVR<br>
svr_linear = SVR(kernel='linear')

In [81]:
from sklearn.svm import SVR

# Train Linear SVR
svr_linear = SVR(kernel='linear')
svr_linear.fit(X_train_scaled, Y_train)

print("Linear SVR model trained successfully")

Linear SVR model trained successfully


<b>Task 5: Predict House Prices</B><br>
Generate predictions for the test set.

In [82]:
# Predict house prices on test set
Y_pred = svr_linear.predict(X_test_scaled)

print("Predictions generated successfully")

# Show first 10 predictions
print("First 10 predictions:", Y_pred[:10])

Predictions generated successfully
First 10 predictions: [0.57328287 1.61361203 2.63246436 2.71669389 2.39888887 1.9803795
 2.48407358 1.95114536 2.78481939 3.82161628]


<b>Task 6: Evaluate Model</b><br>
Compute:<br>
1. MAE (Mean Absolute Error)
2. MSE (Mean Squared Error)
3. RMSE (Root Mean Squared Error)
4. R² Score
from sklearn.metrics import mean_absolute_error

In [83]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

# 1. MAE
mae = mean_absolute_error(Y_test, Y_pred)

# 2. MSE
mse = mean_squared_error(Y_test, Y_pred)

# 3. RMSE
rmse = np.sqrt(mse)

# 4. R² Score
r2 = r2_score(Y_test, Y_pred)

# Print results
print("Mean Absolute Error (MAE):", mae)
print("Mean Squared Error (MSE):", mse)
print("Root Mean Squared Error (RMSE):", rmse)
print("R² Score:", r2)

Mean Absolute Error (MAE): 0.5119686230334923
Mean Squared Error (MSE): 0.5792224848666966
Root Mean Squared Error (RMSE): 0.7610666757037103
R² Score: 0.5579834277049536


<b>Task 7: Train RBF SVR</b><br>
svr_rbf = SVR(kernel='rbf')<br>
Evaluate using the same metrics.

In [84]:
from sklearn.svm import SVR
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

# Train RBF SVR
svr_rbf = SVR(kernel='rbf')
svr_rbf.fit(X_train_scaled, Y_train)

# Predictions
Y_pred_rbf = svr_rbf.predict(X_test_scaled)

# Evaluation

mae = mean_absolute_error(Y_test, Y_pred_rbf)
mse = mean_squared_error(Y_test, Y_pred_rbf)
rmse = np.sqrt(mse)
r2 = r2_score(Y_test, Y_pred_rbf)

print("RBF SVR Results:")
print("MAE:", mae)
print("MSE:", mse)
print("RMSE:", rmse)
print("R² Score:", r2)

RBF SVR Results:
MAE: 0.39859828301457567
MSE: 0.3570026426754463
RMSE: 0.5974969813107396
R² Score: 0.7275639524733044


<b>Task 8: Compare Results</b><br>
Create a table:
| MODEL | MAE | RMSE| R<sup>2</Sup>      |
|----|-------|-----|-----------|
| Linear SVR  |  |   |   |
| RBF SVR  |    |   |     |


In [85]:
import pandas as pd
import numpy as np
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Linear SVR predictions already computed: Y_pred
# RBF SVR predictions already computed: Y_pred_rbf

# Metrics for Linear SVR
mae_linear = mean_absolute_error(Y_test, Y_pred)
rmse_linear = np.sqrt(mean_squared_error(Y_test, Y_pred))
r2_linear = r2_score(Y_test, Y_pred)

# Metrics for RBF SVR
mae_rbf = mean_absolute_error(Y_test, Y_pred_rbf)
rmse_rbf = np.sqrt(mean_squared_error(Y_test, Y_pred_rbf))
r2_rbf = r2_score(Y_test, Y_pred_rbf)

# Create comparison table
results = pd.DataFrame({
    "MODEL": ["Linear SVR", "RBF SVR"],
    "MAE": [mae_linear, mae_rbf],
    "RMSE": [rmse_linear, rmse_rbf],
    "R2": [r2_linear, r2_rbf]
})

print(results)

        MODEL       MAE      RMSE        R2
0  Linear SVR  0.511969  0.761067  0.557983
1     RBF SVR  0.398598  0.597497  0.727564


<b>Task 9: Effect of ε (Epsilon)</b><br>
Create a table:
| MODEL | MAE |
|----|-------|
| 0.01  |     |
| 0. 1 |    |  
|0.5 | |
|1 | |

In [86]:
from sklearn.svm import SVR
from sklearn.metrics import mean_absolute_error
import pandas as pd

eps_values = [0.01, 0.1, 0.5, 1]
results = []

for eps in eps_values:
    model = SVR(kernel='rbf', epsilon=eps)
    model.fit(X_train_scaled, Y_train)

    Y_pred = model.predict(X_test_scaled)
    mae = mean_absolute_error(Y_test, Y_pred)

    results.append([eps, mae])

# Create table
df_results = pd.DataFrame(results, columns=["ε (epsilon)", "MAE"])

print(df_results)

   ε (epsilon)       MAE
0         0.01  0.398185
1         0.10  0.398598
2         0.50  0.421449
3         1.00  0.533678


You submission should also include the following:<br>
1. A one-page summary comparing Logistic Regression, SVC, and SVR.
# One-Page Summary: Logistic Regression, SVC, and SVR Comparison

## 1. Logistic Regression (Classification Model)
Logistic Regression is a linear classification algorithm that predicts the probability of a class using the sigmoid function. It is mainly used for binary and multi-class classification problems.

- **Type:** Linear classifier  
- **Output:** Discrete class labels (0/1 or multi-class)  
- **Strengths:**
  - Simple and fast
  - Easy to interpret
  - Works well for linearly separable data  
- **Limitations:**
  - Poor performance on non-linear data
  - Requires feature scaling for best performance  

---

## 2. Support Vector Classifier (SVC)
SVC is a powerful classification algorithm that finds the optimal hyperplane that maximizes the margin between classes. It supports different kernels to handle both linear and non-linear problems.

- **Type:** Classification model  
- **Output:** Class labels  
- **Kernels Used:**
  - Linear kernel
  - RBF kernel  
- **Strengths:**
  - High accuracy on complex datasets
  - Works well in high-dimensional spaces
  - Kernel trick enables non-linear classification  
- **Limitations:**
  - Computationally expensive on large datasets
  - Requires tuning of parameters (C, gamma)

---

## 3. Support Vector Regression (SVR)
SVR is the regression version of SVM. Instead of predicting classes, it predicts continuous values such as housing prices.

- **Type:** Regression model  
- **Output:** Continuous numerical values  
- **Kernels Used:**
  - Linear SVR
  - RBF SVR  
- **Strengths:**
  - Handles non-linear regression well
  - Robust to outliers using epsilon-insensitive loss
  - Flexible with kernel selection  
- **Limitations:**
  - Sensitive to hyperparameters (C, epsilon, gamma)
  - Slower training on large datasets  

---

## Overall Comparison

| Model | Task Type | Output | Strength | Weakness |
|------|----------|--------|----------|----------|
| Logistic Regression | Classification | Class labels | Simple, interpretable | Limited for non-linear patterns |
| SVC | Classification | Class labels | High accuracy, flexible kernels | Computational cost |
| SVR | Regression | Continuous values | Flexible, robust | Requires tuning |

---